import Head from "next/head";

const DefaultPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>something h1</h2>
        <span>something span</span>
      </main>
    </>
  );
};

export default DefaultPage;
